## Combine all datasets and Train Test Spilt

In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import sys
import numpy as np
sys.path.append('../../')   # Add parent directory to Python path
from utils.preprocessing import *
from utils.segmentation import *
from utils.visualization import *
import pickle
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder
from keras.utils import to_categorical
from sklearn.model_selection import train_test_split

np.random.seed(42)  # For reproducibility


In [4]:
def select_random_samples(data, n=90):
    indices = np.random.choice(data.shape[0], n, replace=False)
    return data[indices]

## 1. Combine all datasets

In [3]:
data = np.load('../../data/Curb/P3/handlebar/Accelerometer/segments_100hz_1s_50overlap.npz')
data_curb_0 = data['segments_0']
data_curb_1 = data['segments_1']
print(data_curb_0.shape, data_curb_1.shape)

(93, 100, 3) (93, 100, 3)


In [10]:
data= np.load('../../data/RoadRoughness/Raw/Asphalt/P1/segments_100hz_1s_50overlap.npz')
data_asphalt= data['segments']
data_asphalt = select_random_samples(data_asphalt, 93)
data= np.load('../../data/RoadRoughness/Raw/Cobblestone/P1/segments_100hz_1s_50overlap.npz')
data_cobblestone= data['segments']
data_cobblestone = select_random_samples(data_cobblestone, 93)
data= np.load('../../data/RoadRoughness/Raw/CompactGravel/P1/segments_100hz_1s_50overlap.npz')
data_compact_gravel= data['segments']
data_compact_gravel = select_random_samples(data_compact_gravel, 93)
data= np.load('../../data/RoadRoughness/Raw/Dirt/P1/segments_100hz_1s_50overlap.npz')
data_Dirt= data['segments']
data_Dirt = select_random_samples(data_Dirt, 93)
data= np.load('../../data/RoadRoughness/Raw/PavingStone/P1/segments_100hz_1s_50overlap.npz')
data_PavingStone= data['segments']
data_PavingStone = select_random_samples(data_PavingStone, 93)



In [11]:
# Add labels
# Assign labels for each surface type
datasets = [
    (data_curb_0, "curb_0"),
    (data_curb_1, "curb_1"),
    (data_asphalt, "asphalt"),
    (data_cobblestone, "cobblestone"),
    (data_compact_gravel, "compact_gravel"),
    (data_Dirt, "dirt"),
    (data_PavingStone, "paving_stone")
]

# Combine all into a single list of (sensor_values, label)
combined_dataset = []
for data, label in datasets:
    for segment in data:
        combined_dataset.append((segment, label))

In [12]:
# save the combined dataset
with open('../../data/data_1s/combined_dataset.pkl', 'wb') as f:
    pickle.dump(combined_dataset, f)

In [13]:
print("Number of samples:", len(combined_dataset))
print("Shape of first sample's sensor values:", combined_dataset[0][0].shape)
# # Show first 3 samples (sensor values and labels)
# for i in range(3):
#     print(combined_dataset[i][0], combined_dataset[i][1])

from collections import Counter
label_counts = Counter(label for _, label in combined_dataset)
print("Number of samples per label:")
for label, count in label_counts.items():
    print(f"{label}: {count}")

Number of samples: 651
Shape of first sample's sensor values: (100, 3)
Number of samples per label:
curb_0: 93
curb_1: 93
asphalt: 93
cobblestone: 93
compact_gravel: 93
dirt: 93
paving_stone: 93


## 2. Train Test Spilt


In [14]:
# 80% train, 20% test
train_set, test_set = train_test_split(combined_dataset, test_size=0.2, random_state=42, shuffle=True, stratify=[label for data, label in combined_dataset])
print(len(train_set), len(test_set))
# Separate sensor values and labels
X_train = [x for x, _ in train_set]
y_train = [label for _, label in train_set]
X_test = [x for x, _ in test_set]
y_test = [label for _, label in test_set]
print(f"Label train: {len(y_train)}, Label test: {len(y_test)}")

520 131
Label train: 520, Label test: 131


In [15]:
# save the train and test sets
with open('../../data/data_1s/train_set.pkl', 'wb') as f:
    pickle.dump(train_set, f)
with open('../../data/data_1s/test_set.pkl', 'wb') as f:
    pickle.dump(test_set, f)


## 3. Normalise dataset

In [16]:
X_train[0]

array([[0.27970582, 4.12415814, 8.93236776],
       [0.27978636, 4.12417064, 8.93233769],
       [0.2798669 , 4.12418315, 8.93230763],
       [0.27994744, 4.12419565, 8.93227757],
       [0.28002798, 4.12420815, 8.9322475 ],
       [0.28010852, 4.12422065, 8.93221744],
       [0.28018906, 4.12423316, 8.93218738],
       [0.2802696 , 4.12424566, 8.93215731],
       [0.28035014, 4.12425816, 8.93212725],
       [0.28043068, 4.12427066, 8.93209719],
       [0.28051122, 4.12428317, 8.93206712],
       [0.28059176, 4.12429567, 8.93203706],
       [0.2806723 , 4.12430817, 8.932007  ],
       [0.28075284, 4.12432067, 8.93197693],
       [0.28083339, 4.12433318, 8.93194687],
       [0.28091393, 4.12434568, 8.93191681],
       [0.28099447, 4.12435818, 8.93188674],
       [0.28107501, 4.12437069, 8.93185668],
       [0.28115555, 4.12438319, 8.93182662],
       [0.28123609, 4.12439569, 8.93179656],
       [0.28131663, 4.12440819, 8.93176649],
       [0.28139717, 4.1244207 , 8.93173643],
       [0.

In [57]:
X_train_array = np.stack(X_train)
print(X_train_array.shape)
print(X_train_array[0])

(1060, 50, 3)
[[-2.94318687  4.45824211  5.85580769]
 [-2.94290638  4.458214    5.85604172]
 [-2.94262588  4.45818589  5.85627574]
 [-2.94234539  4.45815778  5.85650977]
 [-2.9420649   4.45812967  5.85674379]
 [-2.94178441  4.45810157  5.85697782]
 [-2.94150391  4.45807346  5.85721184]
 [-2.94122342  4.45804535  5.85744586]
 [-2.94094293  4.45801724  5.85767989]
 [-2.94066243  4.45798913  5.85791391]
 [-2.94038194  4.45796102  5.85814794]
 [-2.94010145  4.45793292  5.85838196]
 [-2.93982095  4.45790481  5.85861599]
 [-2.93954046  4.4578767   5.85885001]
 [-2.93925997  4.45784859  5.85908403]
 [-2.93897947  4.45782048  5.85931806]
 [-2.93869898  4.45779237  5.85955208]
 [-2.93841849  4.45776426  5.85978611]
 [-2.93813799  4.45773616  5.86002013]
 [-2.9378575   4.45770805  5.86025416]
 [-2.93757701  4.45767994  5.86048818]
 [-2.93729652  4.45765183  5.8607222 ]
 [-2.93701602  4.45762372  5.86095623]
 [-2.93673553  4.45759561  5.86119025]
 [-2.93645504  4.45756751  5.86142428]
 [-2.936174

In [17]:
# Stack X_train to shape (num_samples, segment_length, num_channels)
X_train_array = np.stack(X_train)  # shape: (N, L, C)

# Reshape to 2D for scaler: (N*L, C)
# Your sensor data is 3D: (N, L, C) where, N = number of samples, L = segment length (timesteps), C = number of channels (features per timestep)
N, L, C = X_train_array.shape
X_train_reshaped = X_train_array.reshape(-1, C)
# you are converting your 3D array (N, L, C) into a 2D array with shape (N*L, C).
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train_reshaped)

# Reshape back to original shape
X_train_normalized = X_train_scaled.reshape(N, L, C)

# 4. Labels from string to integer

In [18]:
label_encoder = LabelEncoder()
y_train_int = label_encoder.fit_transform(y_train)
y_test_int = label_encoder.transform(y_test)

print("Classes:", label_encoder.classes_)
print("First 10 y_train_int:", y_train_int[:10])
print("First 10 y_test_int:", y_test_int[:10])
for idx, label in enumerate(label_encoder.classes_):
    print(f"{idx}: {label}")


Classes: ['asphalt' 'cobblestone' 'compact_gravel' 'curb_0' 'curb_1' 'dirt'
 'paving_stone']
First 10 y_train_int: [6 3 2 3 5 0 2 0 1 4]
First 10 y_test_int: [5 4 1 3 5 4 6 0 6 0]
0: asphalt
1: cobblestone
2: compact_gravel
3: curb_0
4: curb_1
5: dirt
6: paving_stone


## 5: One-hot encode the labels

In [19]:
y_train_onehot = to_categorical(y_train_int)
y_test_onehot = to_categorical(y_test_int)

print(y_train_onehot.shape)
print(y_test_onehot.shape)

(520, 7)
(131, 7)


In [20]:
# Randomly select an index and check that the one-hot encoding matches the original label
r = np.random.randint(len(y_train_int))
assert y_train_onehot[r].argmax() == y_train_int[r]
r = np.random.randint(len(y_test_int))
assert y_test_onehot[r].argmax() == y_test_int[r]

## 6. Save train, test data and labels

In [21]:
with open('../../data/data_1s/X_train_normalized.pkl', 'wb') as f:
    pickle.dump(X_train_normalized, f)
with open('../../data/data_1s/X_test_original.pkl', 'wb') as f:
    pickle.dump(X_test, f)
with open('../../data/data_1s/y_train_onehot.pkl', 'wb') as f:
    pickle.dump(y_train_onehot, f)
with open('../../data/data_1s/y_test_onehot.pkl', 'wb') as f:
    pickle.dump(y_test_onehot, f)

## 6. Train, validation Spilt

In [22]:
# Load data
with open('../../data/data_1s/X_train_normalized.pkl', 'rb') as f:
    train_data = pickle.load(f)
with open('../../data/data_1s/y_train_onehot.pkl', 'rb') as f:
    train_labels = pickle.load(f)

In [23]:
X_train, X_val, y_train, y_val = train_test_split(
    train_data,
    train_labels,
    test_size=0.2,           # 20% for validation
    random_state=42,
    shuffle=True
)

print("Train shape:", X_train.shape, y_train.shape)
print("Validation shape:", X_val.shape, y_val.shape)

Train shape: (416, 100, 3) (416, 7)
Validation shape: (104, 100, 3) (104, 7)


In [24]:
with open('../../data/data_1s/X_train_normalized.pkl', 'wb') as f:
    pickle.dump(X_train, f)
with open('../../data/data_1s/X_val_normalized.pkl', 'wb') as f:
    pickle.dump(X_val, f)
with open('../../data/data_1s/y_train_onehot.pkl', 'wb') as f:
    pickle.dump(y_train, f)
with open('../../data/data_1s/y_val_onehot.pkl', 'wb') as f:
    pickle.dump(y_val, f)